### ISSUE TITLE
Placement rules tracking issue

### ISSUE THREAD

**Issue by disksing** [pingcap/pd#2017]
List PR merge process of placement rules.
- [x] add rule definitions https://github.com/pingcap/pd/pull/1834
- [x] remove stale code https://github.com/pingcap/pd/pull/1855
- [x] add manager and FitRegion interface https://github.com/pingcap/pd/pull/1865
- [x] add API support https://github.com/pingcap/pd/pull/1894
- [x] consider placement rules when verify region healthy https://github.com/pingcap/pd/pull/1897
- [x] add FitRegion implementation https://github.com/pingcap/pd/pull/1904
- [x] make schedulers aware of placement rules https://github.com/pingcap/pd/pull/1999
- [x] add rule checker https://github.com/pingcap/pd/pull/2042
- [x] make checkers aware of placement rules https://github.com/pingcap/pd/pull/2051
